# It uses node:18-alpine as the base image for the frontend React.js application
# Use an appropriate base image for Node.js, such as node:latest
FROM node:latest

# Creating the working directory named `app`
WORKDIR /app

# Copying package.json and package-lock.json to the working directory `app`
COPY package*.json /app/

# Installing dependencies
RUN npm install

# Copying the rest of the application code
COPY . .

# Exposing port 3000
EXPOSE 3000

# Command to start the Docker container for the frontend React.js application
CMD ["npm", "start"]
