# Use Node.js as the base image
FROM node:latest AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json into the working directory
COPY package*.json ./

# Install npm packages
RUN npm install

# Copy the rest of the code into the working directory
COPY . .

# Build the React application
RUN npm run build

# Run stage
FROM nginx:alpine

# Copy the build output to replace the default Nginx contents.
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]