# Use a base image compatible with linux/amd64
FROM --platform=linux/amd64 ubuntu:latest

# Creating the working directory named `app`
WORKDIR /app

# Copying package.json and package-lock.json to the working directory `app`
COPY package*.json /app/

# Installing dependencies
RUN npm install

# Copying the rest of the application code
COPY . .

# Exposing port 3000
EXPOSE 3000

# Command to start the Docker container for the frontend React.js application
CMD ["npm", "start"]
