name: test-sprint1
run-name: ${{ github.actor }} is testing sprint 1
on: 
  pull_request:
    branches: 
      - main
jobs:
  test-sprint1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
