name: Test-Sprint2
run-name: ${{ github.actor }} is testing sprint 2
on: 
  pull_request:
    branches: 
      - main
jobs:
  test-sprint2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: '21'
=======
          node-version: '20'
>>>>>>> f10eec56330dc84585a125ccf3aa43bfadc6f3d1
      - run: npm install
      - run: npm install --save-dev @babel/plugin-proposal-private-property-in-object 
        working-directory: mcdonalds2
      # - run: npm start
      #   working-directory: mcdonalds2
      - run: npm test
        working-directory: mcdonalds2