
name: Test-Sprint7
run-name: ${{ github.actor }} is testing sprint 7


on: 
  pull_request:
    branches: 
      - main
      - yenyilee_sprint8

permissions:
  id-token: write
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
        env:
          API_KEY: ${{ secrets.API_KEY }} # Access the API key from GitHub Secret
      
      - name: Run tests
        run: npm test
        working-directory: ./frontend/src
        env:
          API_KEY: ${{ secrets.API_KEY }} # Access the API key from GitHub Secret

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./frontend/src/__tests__/coverage/lcov-report

  build-and-deploy:
    needs: test  # Ensures this job runs only after the test-sprint4 job completes successfully.
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: cdf15b8f-e8bc-4478-af95-ce9a3fd7d103
          tenant-id: 02e496e0-bb8f-4ec3-bf4d-6e3cd4bd4ba4
          subscription-id: ffc52f45-ea26-4ffd-ba5b-b79c1134abc3
  
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: cosi103a
          containerAppName: mcdonalds
          resourceGroup: myResourceGroup 
          dockerfilePath: dockerfile.Dockerfile

# Smoke test
  smoke-test:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # Install any dependencies required for your smoke tests here
      - name: Install Dependencies
        run: npm install
      
      - name: Run Smoke Tests
        run: 
          npm run smoke-test
        working-directory: ./frontend
  
  # Switch Traffic 
  traffic-switch:
    needs: smoke-test
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        run: az login
        # uses: azure/login@v1
        # with:
        #   client-id: cdf15b8f-e8bc-4478-af95-ce9a3fd7d103
        #   tenant-id: 02e496e0-bb8f-4ec3-bf4d-6e3cd4bd4ba4
        #   subscription-id: ffc52f45-ea26-4ffd-ba5b-b79c1134abc3
      

      - name: Switch traffic to new version
        run: |
          az webapp traffic-routing set \
          --distribution staging=100 \
          --ids "/subscriptions/ffc52f45-ea26-4ffd-ba5b-b79c1134abc3/resourceGroups/myResourceGroup/providers/Microsoft.App/containerApps/mcdonalds" \
